name: flake8

on: 
  push:
    paths:
      - 'hundun/**'

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - run: pip install flake8
      - run: flake8 hundun
